version: '3.3'

services:
  reverse-proxy:
    image: traefik:1.7-alpine
    command:
      - --api
      - --docker
      - --docker.exposedbydefault=false
    ports:
      - 80:80
      - 443:443
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./cert/traefik.docker.pem:/etc/ssl/traefik.docker.crt
      - ./cert/traefik.docker-key.pem:/etc/ssl/traefik.docker.key
      - ./../nginx/cert/magazine.docker.pem:/etc/ssl/magazine.docker.crt
      - ./../nginx/cert/magazine.docker-key.pem:/etc/ssl/magazine.docker.key
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
